### ISSUE TITLE
multiple ini_write

### ISSUE THREAD

**Issue by roncoa** [SK-SpeedBit/SPIFFS_ini#1]
how can i handle multiple ini_write writing?
I need to write over 50 keys simultaneously.

I tried this, but it doesn't work.
Writes only the first key.

if (ini_open (Config_ini)) {
ini_write(SezioneConfigurazione, "avvio", configuration.avvio);
ini_write(SezioneConfigurazione, "ssid", configuration.ssid);
ini_write(SezioneConfigurazione, "password", configuration.password);
ini_write(SezioneConfigurazione, "staticip", configuration.staticip);
ini_write(SezioneConfigurazione, "ip", configuration.ip);
...........
}

**Comment by SK-SpeedBit** [comment]
Hi
It looks like you're doing everything right.
First of all, check the amount of memory on the disk.
Each record creates a NEW ini file and finally deletes the old one.
So you need disk space monimum 2 * file size ini = 50k + 50k => 100k
Remember to close the file -> ini_close ();
Let me know if everything went well.
Unfortunately, I didn't check such large files, but together we will try to
find the reason
Regards,
    Slawek

**Comment by roncoa** [comment]
should ini_open and ini_close be used with both ini_read and ini_write?
If the .ini file does not exist, do ini_open or ini_write create it?
Do you have any small example?

**Comment by roncoa** [comment]
![Immagine 1](https://user-images.githubusercontent.com/19438993/71772547-146e9480-2f4d-11ea-8ac4-1c20483a6d6e.jpg)
You can see that only ini_open and the first ini_write works.
I am using Arduino IDE 1.8.10 with ESP8266 community version 2.6.3

**Comment by roncoa** [comment]
@SK-SpeedBit ,do you have any small examples with some keys?

**Comment by SK-SpeedBit** [comment]
Hi
I have an example of how to read an ini file only.
The write is identical, just use ini_write instead of ini_read.
This is a leftover after testing procedures (checking uppercase and lowercase letters as keys):

      _if (ini_open (directory + filename)) {
        sklog ("File ini ok");
        sklog (ini_read ("Files", "CapFile", "nothing"));
        sklog (ini_read ("win", "WideState", "ee"));
        sklog (ini_read ("com", "Parity", "--1"));
        sklog (ini_read ("com", "DATABITS", "--2"));
        sklog (ini_read ("SlaWekK", "INI NEW file", "--- 3"));
        sklog (ini_read ("SlaWekK", "no key", "--- 4"));
        sklog (ini_read ("No Sec", "no key", "--- 5"));
        ini_close ();
      }
      else sklog ("File ini error");_

Note the write time that I calculated empirically during the tests:
**The readout time of a SINGLE variable is approx. 50 ms.
The recording time is longer and is about 500ms (0.5s !!!) **

If you have a lot of variables to write (I hope you also have disk space) and use WatchDog then you should check if WatchDog does not reset the processor. Refresh WatchDog after each write line so that the processor does not restarted.
This is very important!

**Comment by roncoa** [comment]
Between one ini_write and another, do I have to put delays?

**Comment by SK-SpeedBit** [comment]
No. A delay is not recommended and is unnecessary.
Writing (due to the fact that we write to FLASH memory, also that between the memory (disk) and the program are drivers and the ini file saving library) takes a lot of time.
Therefore, if you have added WDT (WatchDog) support to your program, check if it does not reset the processor due to long write times. If WDT is to be active, either run it after reading / writing the ini file, or block it for the time of these operations or give a longer WDT time and after each write / read line add a WDT refresh line.
You can find more information about WDT in the search engine.
You have one of the links from the search engine below:
[https://techtutorialsx.com/2017/01/21/esp8266-watchdog-functions/](https://techtutorialsx.com/2017/01/21/esp8266-watchdog-functions/)
In my opinion this should solve your problem.

**Comment by SK-SpeedBit** [comment]
Use the latest version. It runs entirely in RAM and is very fast. It doesn't take that long to save the file.
